name = "blog-pages"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"

[build.environment_variables]
NODE_VERSION = "18"

compatibility_flags = ["nodejs_compat"] 